apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
  labels:
    app: mydeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydeploy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: mydeploy
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: addressbook
        image: bitnami/tomcat:latest
        ports:
        - containerPort: 8080
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
